from __future__ import annotations

import json
from pathlib import Path
from typing import Any

INDO_FIDUCIAL_TEACHER_SCHEMA_VERSION = (
    "motionos.indo-fiducial-teacher-dataset.v1"
)


def extract_fiducial_teacher_labels(
    camera_journal_path: str | Path,
    output_path: str | Path,
) -> dict[str, Any]:
    """Extract QR-derived deck/roller labels from a MotionOS camera journal.

    Only pose events carrying fiducial-measured equipment geometry are
    exported. The original camera frame sequence and monotonic timestamp are
    preserved so labels can be joined back to the recorded movie without
    inventing wall-clock timing.
    """

    journal = Path(camera_journal_path)
    observations: list[dict[str, Any]] = []
    pose_event_count = 0
    equipment_event_count = 0
    skipped_non_fiducial_count = 0
    first_device_time_ns: int | None = None

    with journal.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            text = line.strip()
            if not text:
                continue

            try:
                envelope = json.loads(text)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"invalid JSONL at line {line_number}: {exc.msg}"
                ) from exc

            if not isinstance(envelope, dict):
                continue
            if envelope.get("stream") != "/camera/pose3d":
                continue
            pose_event_count += 1

            payload = envelope.get("payload")
            if not isinstance(payload, dict):
                continue
            equipment = payload.get("indo_board_equipment")
            if not isinstance(equipment, dict):
                continue
            equipment_event_count += 1

            if not _is_fiducial_equipment(equipment):
                skipped_non_fiducial_count += 1
                continue

            session_id = envelope.get("session_id")
            device_time_ns = envelope.get("device_time_ns")
            source_frame_sequence = payload.get(
                "source_frame_sequence"
            )
            if not isinstance(session_id, str) or not session_id:
                continue
            if not isinstance(device_time_ns, (int, float)):
                continue
            if not isinstance(source_frame_sequence, (int, float)):
                continue

            device_time_ns_int = round(float(device_time_ns))
            source_frame_index = round(
                float(source_frame_sequence)
            )
            if device_time_ns_int < 0 or source_frame_index < 0:
                continue

            if first_device_time_ns is None:
                first_device_time_ns = device_time_ns_int

            runtime_equipment = dict(equipment)
            runtime_equipment["sequence"] = source_frame_index
            runtime_equipment["device_time_ns"] = device_time_ns_int

            observations.append(
                {
                    "source_id": session_id,
                    "frame_index": source_frame_index,
                    "camera_pose_sequence": envelope.get(
                        "sequence"
                    ),
                    "device_time_ns": device_time_ns_int,
                    "time_s": (
                        device_time_ns_int - first_device_time_ns
                    )
                    / 1_000_000_000,
                    "review_status": "fiducial_teacher",
                    "indo_board_equipment": runtime_equipment,
                }
            )

    observations.sort(
        key=lambda item: (
            str(item["source_id"]),
            int(item["frame_index"]),
        )
    )

    payload = {
        "schema_version":
            INDO_FIDUCIAL_TEACHER_SCHEMA_VERSION,
        "source_journal": journal.name,
        "pose_event_count": pose_event_count,
        "equipment_event_count": equipment_event_count,
        "skipped_non_fiducial_count":
            skipped_non_fiducial_count,
        "observation_count": len(observations),
        "observations": observations,
        "claim_boundary": (
            "These are image-space teacher labels generated by visible QR "
            "fiducials. They are not human-reviewed markerless detections, "
            "metric camera calibration, force measurements, or biomechanics "
            "ground truth."
        ),
    }

    _write_json(output_path, payload)
    return payload


def _is_fiducial_equipment(
    equipment: dict[str, Any],
) -> bool:
    deck = equipment.get("deck")
    roller = equipment.get("roller")
    if not isinstance(deck, dict) or not isinstance(roller, dict):
        return False
    return (
        deck.get("provenance") == "fiducial_measured"
        and roller.get("provenance") == "fiducial_measured"
    )


def _write_json(
    path: str | Path,
    payload: dict[str, Any],
) -> None:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
